import Head from 'next/head'
import Banner from '../components/Banner'
import Footer from '../components/Footer'
import Header from '../components/Header'
import LargeCard from '../components/LargeCard'
import MediumCard from '../components/MediumCard'
import SmallCard from '../components/SmallCard'

export default function Home({ exploreData, cardsData }) {
  // console.log(exploreData);
  return (
    <div>
      <Head>
        <title>Airbnb - Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        {/* for post picture */}
        <meta property="og:title" content="" />
        <meta property="og:type" content="" />
        <meta property="og:image" content="/airbnb-logo.png" />
        <meta name="twitter:card" content="summary_large_image" />

        <meta property="og:description" content="" />
        <meta name="twitter:image:alt" content="" />
      </Head>

      {/* header */}
      <Header />

      {/* banner */}
      <Banner />


      {/* main sectins */}
      <main className='max-w-7xl mx-auto px-8 sm:px-16'>

        {/* for small card */}
        <section className='pt-6'>
          <h2 className='text-4xl font-semibold pb-5'>Explore Nearby</h2>

          {/* pull some data from server - API ENDPOINT */}
          <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4'>
            {exploreData?.map((item) => (
              <SmallCard key={item.img} img={item.img} location={item.location} distance={item.distance} />
            ))}
          </div>
        </section>


        {/* for scrollable Medium card */}
        <section>
          {/* to hide the scroll bar view... use plugin "npm i tailwind-scrollbar-hide" */}
          <h2 className='text-4xl font-semibold py-8'>Live Anywhere</h2>

          <div className='flex overflow-scroll scrollbar-hide space-x-3 p-3 -ml-3'>
            {cardsData?.map((item) => (
              <MediumCard key={item.img} img={item.img} title={item.title} />
            ))}
          </div>
        </section>


        {/* for Large card */}
        <LargeCard img={'https://links.papareact.com/4cj'} title={'The Greatest Outdoors'} description={'Wishlists curated by Airbnb'} buttonText={'Get Inspired'}  />

      </main>

      <Footer />
    </div>
  )
}




// NOTE: only works under pages...
// SERVER SIDE RENDERING >> getServerSideProps
// STATIC SIDE RENDERING >> getStaticProps

export async function getStaticProps() {
  // getting that data from the link and parsing (taking only json)
  {/* for small card */ }
  const exploreData = await fetch('https://links.papareact.com/pyp').then((res) => res.json())

  {/* for scrollable Medium card */ }
  const cardsData = await fetch('https://links.papareact.com/zp1').then((res) => res.json())


  // sending the data to the Home function as a props
  return {
    props: {
      exploreData,
      cardsData
    }
  }
}
