import { useRouter } from 'next/router';
import React from 'react';
import Footer from '../components/Footer';
import Header from '../components/Header'
import { format } from 'date-fns'
import InfoCard from '../components/InfoCard';
import Map from '../components/Map';
import Head from 'next/head'

function Search({ searchResults }) {
    // console.log(searchResults);
    // to get the data from url
    const router = useRouter()

    const { endDate, location, noOfGuest, startDate } = router.query

    // console.log(router.query);
    {/* 
        Object:-
            endDate: "2022-01-30T18:30:00.000Z"
            location: "Panvel"
            noOfGuest: "1"
            startDate: "2022-01-22T18:30:00.000Z"
            [[Prototype]]: Object 
    */}

    // to convert the date in proper format
    const formattedStartDate = format(new Date(startDate), "dd MMMM yy") //new Date means create date object and passing the start date

    const formattedEndDate = format(new Date(endDate), "dd MMMM yy") //new Date means create date object and passing the end date

    const range = `${formattedStartDate} - ${formattedEndDate}`


    return (
        <div>
            <Head>
                <title>Airbnb - {location}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />

                {/* for post picture */}
                <meta property="og:title" content="" />
                <meta property="og:type" content="" />
                <meta property="og:image" content="/airbnb-logo.png" />
                <meta name="twitter:card" content="summary_large_image" />

                <meta property="og:description" content="" />
                <meta name="twitter:image:alt" content="" />
            </Head>


            <Header placeholder={`${location} | ${range} | ${noOfGuest} `} />

            <main className='flex'>
                <section className='flex-grow pt-14 px-6'>
                    <p className='text-xs'>300+ Stays - {range} - for {noOfGuest} guests</p>
                    <h1 className='text-3xl font-semibold mt-2 mb-6'>Stays in {location}</h1>

                    <div className='hidden lg:inline-flex space-x-3 mb-5 text-gray-800 whitespace-nowrap'>
                        {/* whitespace-nowrap >>> if the text is bigger then dont put in new line */}
                        <p className='button'>Cancellation Flexibility</p>
                        <p className='button'>Type of Place</p>
                        <p className='button'>Price</p>
                        <p className='button'>Rooms and Beds</p>
                        <p className='button'>More Filters</p>

                    </div>

                    <div className='flex flex-col'>
                        {searchResults.map((item) => (
                            <InfoCard key={item.img} img={item.img} location={item.location} title={item.title} description={item.description} star={item.star} price={item.price} total={item.total} />
                        ))}
                    </div>
                </section>

                {/* map section */}
                <section className='hidden xl:inline-flex xl:min-w-[600px]'>
                    <Map searchResults={searchResults} />
                </section>
            </main>

            <Footer />
        </div>
    );
}

export default Search;


// SERVER SIDE RENDERING

// context inside getServerSideProps >>> gives us query parameter like router query
export async function getServerSideProps() {
    const searchResults = await fetch('https://links.papareact.com/isz').then((res) => res.json())

    // returning props to Search function above TOP
    return {
        props: {
            searchResults
        }
    }
} 